version: "3.8"

services:
  postgres:
    container_name: creditapplication_db
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=creditapplication
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=123qwe
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
