version: '3.8'
services:
  app:
    container_name: creditapplication
    image: creditapplication
    build: ../
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=db_user
      - POSTGRES_DB=creditapplication
  reactapp:
    build: ../../creditapplication-client
    ports:
      - "3000:3000"
    image: reactapp:react
    container_name: react-container
    command: npm start
